### ISSUE TITLE
TextAnchor issue

### ISSUE THREAD

**Issue by penhorwood** [mapbox/mapbox-maps-flutter#161]
I am getting the following error when running 0.4.3 in debug mode when trying to add a point annotation to the map.  My code uses
```
PointAnnotationOptions(
...
    textAnchor: TextAnchor.BOTTOM_LEFT
)
```

```
Exception has occurred.
PlatformException (PlatformException(IllegalArgumentException, java.lang.IllegalArgumentException: No enum constant com.mapbox.maps.extension.style.layers.properties.generated.TextAnchor.BOTTOM-LEFT, Cause: null, Stacktrace: java.lang.IllegalArgumentException: No enum constant com.mapbox.maps.extension.style.layers.properties.generated.TextAnchor.BOTTOM-LEFT
	at java.lang.Enum.valueOf(Enum.java:257)
	at com.mapbox.maps.extension.style.layers.properties.generated.TextAnchor.valueOf(Unknown Source:2)
	at com.mapbox.maps.plugin.annotation.generated.PointAnnotation.getTextAnchor(PointAnnotation.kt:288)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationControllerKt.toFLTPointAnnotation(PointAnnotationController.kt:833)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationController.create(PointAnnotationController.kt:33)
	at com.mapbox.maps.pigeons.FLTPointAnnotationMessager$_PointAnnotationMessager$-CC.lambda$setup$0(FLTPointAnnotationMessager.java:1283)
	at com.mapbox.maps.pigeons.FLTPointAnnotationMessager$_PointAnnotationMessager$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)
```

**Comment by penhorwood** [comment]
PS D:\android\apps\caminha> flutter doctor -v
[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [Version 10.0.19045.3208], locale en-US)
    • Flutter version 3.10.6 on channel stable at D:\development\flutter-sdk
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 days ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
    • Android SDK at D:\development\Android\sdk
    • Platform android-33, build-tools 33.0.2
    • ANDROID_HOME = D:\development\Android
    • ANDROID_SDK_ROOT = D:\development\Android\Sdk
    • Java binary at: D:\development\java.home\bin\java
    • Java version OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.18+10-adhoc..jdk11u)
    • All Android licenses accepted.

[√] Android Studio (version 2022.2)
    • Android Studio at D:\development\tools\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-9586694)

[√] Connected device (1 available)
    • SM G973U1 (mobile) • RF8M216A2RT • android-arm64 • Android 12 (API 31)

[√] Network resources
    • All expected network resources are available.

• No issues found!
PS D:\android\apps\caminha>

**Comment by smc66** [comment]
Any updates on this???
I am having this exact issue, on Android devices only, with the latest version (0.5.1)

**Comment by penhorwood** [comment]
https://github.com/mapbox/mapbox-maps-flutter/issues/417

@evil159  - This appears to still be happening.  See my comments on the other ticket.  Sorry for the duplicate.

**Comment by O-Hannonen** [comment]
Related to #500 and #455 

Correcting the earlier comment: PR #523 did not actually fix this. That PR only
changed enum encoding for style layers (e.g. `SymbolLayer`), not for annotations.

The crash here (`TextAnchor.valueOf` does not support `[BOTTOM-LEFT]` when using
`PointAnnotationOptions`) was caused by a bug in the native Android Maps SDK's
annotation plugin. It was fixed in Maps SDK 11.14.0 and shipped in
mapbox_maps_flutter 2.10.0

Closing this as fixed now, thanks for reporting and the discussion!
