### ISSUE TITLE
IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner

### ISSUE THREAD

**Issue by amias-samir** [mapbox/mapbox-maps-flutter#259]
```
> Expecting binder but got null!

>   E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Please ensure that the hosting activity/fragment is a valid LifecycleOwner
>                                                                 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.doOnAttached(ViewLifecycleOwner.kt:68)
>                                                                 	at com.mapbox.maps.plugin.lifecycle.ViewLifecycleOwner.<init>(ViewLifecycleOwner.kt:58)
>                                                                 	at com.mapbox.maps.plugin.lifecycle.MapboxLifecyclePluginImpl.registerLifecycleObserver(MapboxLifecyclePluginImpl.kt:30)
>                                                                 	at com.mapbox.maps.plugin.MapPluginRegistry.onAttachedToWindow(MapPluginRegistry.kt:173)
>                                                                 	at com.mapbox.maps.MapController.onAttachedToWindow$sdk_publicRelease(MapController.kt:346)
>                                                                 	at com.mapbox.maps.MapView.onAttachedToWindow(MapView.kt:129)
>                                                                 	at android.view.View.dispatchAttachedToWindow(View.java:21511)
>                                                                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3590)
>                                                                 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3597)
>                                                                 	at android.view.ViewGroup.addViewInner(ViewGroup.java:5408)
>                                                                 	at android.view.ViewGroup.addView(ViewGroup.java:5188)
>                                                                 	at android.view.ViewGroup.addView(ViewGroup.java:5128)
>                                                                 	at android.view.ViewGroup.addView(ViewGroup.java:5100)
>                                                                 	at io.flutter.plugin.platform.PlatformViewsController.configureForTextureLayerComposition(PlatformViewsController.java:648)
>                                                                 	at io.flutter.plugin.platform.PlatformViewsController.access$900(PlatformViewsController.java:49)
>                                                                 	at io.flutter.plugin.platform.PlatformViewsController$1.createForTextureLayer(PlatformViewsController.java:225)
>                                                                 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:128)
>                                                                 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:55)
>                                                                 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
>                                                                 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
>                                                                 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
>                                                                 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
>                                                                 	at android.os.Handler.handleCallback(Handler.java:942)
>                                                                 	at android.os.Handler.dispatchMessage(Handler.java:99)
>                                                                 	at android.os.Looper.loopOnce(Looper.java:211)
>                                                                 	at android.os.Looper.loop(Looper.java:300)
>                                                                 	at android.app.ActivityThread.main(ActivityThread.java:8294)
>                                                                 	at java.lang.reflect.Method.invoke(Native Method)
>                                                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
>                                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
>                                                                 , null, null)
>                                                                 #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
>                                                                 #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
>                                                                 <asynchronous suspension>
>                                                                 #2      TextureAndroidViewController._sendCreateMessage (package:flutter/src/services/platform_views.dart:1100:28)
>                                                                 <asynchronous suspension>
>                                                                 #3      AndroidViewController.create (package:flutter/src/services/platform_views.dart:763:5)
>                                                                 <asynchronous suspension>
>                                                                 #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:790:7)
>                                                                 <asynchronous suspension>
>                                                                 #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
>                                                                 <asynchronous suspension>
```

**Comment by FelixMitze** [comment]
Any updates or this?
Is the pr fixing the issue?

I have the same issue with the package and therefore cannot build a release for my app.
Is there a workaround for this issue, that will work without the current pr?

**Comment by evil159** [comment]
Hi all, this issue should be fixed in https://github.com/mapbox/mapbox-maps-flutter/pull/478, feel free to reopen this ticket if you have any feedback!
