### ISSUE TITLE
How can I add an image to the map?

### ISSUE THREAD

**Issue by dawid-niedzwiecki** [mapbox/mapbox-maps-flutter#30]
I'm trying to add an image (Uint8List) to the maps style, so that I can reference it later in a feature when I assemble a source geojson. This is what I tried:

```dart
    ByteData byteData =
        await rootBundle.load('assets/map_icons/$assetName.png');
    Uint8List image = byteData.buffer.asUint8List();
    // So far everything is okay, the list is correct.
    // But here I struggle with understanding what half of the properties do. The next line throws an error.
    await mapController.style.addStyleImage(
      assetName, // A string (which I later use to reference the image in a geojson source)
      1,
      MbxImage(width: 50, height: 50, data: image),
      true,
      [],
      [],
      null,
    );
    
```
The error thrown is:
```
PlatformException (PlatformException(Throwable, java.lang.Throwable: mismatched image size, Cause: null, Stacktrace: java.lang.Throwable: mismatched image size
	at com.mapbox.maps.mapbox_maps.StyleController.addStyleImage$lambda-49(StyleController.kt:641)
	at com.mapbox.maps.mapbox_maps.StyleController.$r8$lambda$9qzAKUZTMYPcXQ8_jKe8hkSxnyU(Unknown Source:0)
	at com.mapbox.maps.mapbox_maps.StyleController$$ExternalSyntheticLambda0.onStyleLoaded(Unknown Source:17)
	at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:355)
	at com.mapbox.maps.mapbox_maps.StyleController.addStyleImage(StyleController.kt:610)
	at com.mapbox.maps.mapbox_maps.StyleController.addStyleImage(StyleController.kt:17)
	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$-CC.lambda$setup$34(FLTMapInterfaces.java:7898)
	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$$ExternalSyntheticLambda20.onMessage(Unknown Source:2)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
, null))
```

**Comment by dawid-niedzwiecki** [comment]
I also tried it like this:

```dart
        img.Image? parsedImage = img.decodeImage(imageData);
        if (parsedImage == null) return;
        int h = parsedImage.height;
        int w = parsedImage.width;

        // Add the image to the map:
        await mapController.style.addStyleImage(
          'customMarker',
          1,
          MbxImage(width: w, height: h, data: imageData),
          true,
          [],
          [],
          null,
        );
        ```
        
       And it worked! But the images are purely black, no colors...

**Comment by AnEpicName** [comment]
I remember having that same issue but in the web, and the solution was to set the SDF to `false`, try passing the 4th parameter to false.

**Comment by dawid-niedzwiecki** [comment]
> I remember having that same issue but in the web, and the solution was to set the SDF to `false`, try passing the 4th parameter to false.

That worked for me, thanks!

**Comment by kamami** [comment]
That did not work for me... 
`  map.style.addStyleImage(
      "chargerPublic",
      2.1,
      MbxImage(width: 0, height: 0, data: listChargerPublic),
      false,
      [],
      [],
      null);`
