### ISSUE TITLE
Conflict Between mapbox-maps-flutter Library and Mainstream Location Libraries (e.g., location, geolocator)

### ISSUE THREAD

**Issue by shihanjun19** [mapbox/mapbox-maps-flutter#310]
**Content:**
While testing with mapbox-maps-flutter/example/, I encountered conflicts between the mapbox-maps-flutter library and common location libraries. After integrating either location: ^5.0.3 or geolocator: ^10.1.0 into my project, I noticed that the animated route line page in the mapbox example failed to obtain correct location data during real device debugging.

**Steps to Reproduce:**
1. Add either location: ^5.0.3 or geolocator: ^10.1.0 to the project's pubspec.yaml file.
2. Run the project.
3. Observe that mapbox is unable to acquire location data.

**Error Log:**
```
I/Mapbox  (18814): [maps-core]: Using OpenGL render backend
I/Mapbox  (18814): [threading]: MapboxRenderThr priority is now -10
I/Mapbox  (18814): [maps-android\Mbgl-RenderThread]: Native renderer created.
I/Mapbox  (18814): [maps-android\Mbgl-RenderThread]: onSurfaceCreated: Android surface was processed.
I/Mapbox  (18814): [threading]: Worker 1 priority is now 4
I/Mapbox  (18814): [maps-core]: {MapboxRenderThr}[General]: GPU Identifier: Mali-G76
I/Mapbox  (18814): [threading]: ResourceLoaderT priority is now 4
I/Mapbox  (18814): [threading]: TileStoreFileSo priority is now 4
E/flutter (18814): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (18814): #0      PuckPosition.getPuckPosition (package:mapbox_maps_example/utils.dart:92:42)
E/flutter (18814): <asynchronous suspension>
E/flutter (18814): #1      AnimatedRouteState.refreshTrackLocation.<anonymous closure> (package:mapbox_maps_example/animated_route.dart:130:26)
E/flutter (18814): <asynchronous suspension>
```

**Device Information:**
- Phone: HUAWEI P30
- OS: HarmonyOS 3.0.0

**Comment by shihanjun19** [comment]
I'm experiencing a potential conflict between the mapbox-maps-flutter and geolocator libraries when running my Flutter project in debug mode.

**Debug Mode Behavior:**
- When location access is set to "Allow only while using the app," one library successfully listens for location updates, but the other fails to receive any location data.
- However, when location access is set to "Allow all the time," both libraries function correctly and can obtain location data.

**Release Mode Behavior:**
- In release mode, everything appears to function normally. Both libraries are able to successfully fetch location data.

**Seeking Guidance:**
I'm looking for advice on how to diagnose and resolve this issue. What steps can I take to identify the cause of this conflict in debug mode? Any suggestions or similar experiences would be greatly appreciated.

**Comment by NhaPCS** [comment]
I got an issue when using Mapbox with geolocator, the location is not reported correctly. Are there any updates on this?
