### ISSUE TITLE
accessing Telemetry Settings cause app crash

### ISSUE THREAD

**Issue by vchrisb** [mapbox/mapbox-maps-flutter#403]
Hi,

when trying to access the Telemetry Settings in the attribution, the app is crashing with:

```
E/AndroidRuntime( 4829): FATAL EXCEPTION: main
E/AndroidRuntime( 4829): Process: com.mapbox.maps.flutter.example, PID: 4829
E/AndroidRuntime( 4829): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:926)
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:889)
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:772)
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
E/AndroidRuntime( 4829): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:436)
E/AndroidRuntime( 4829): 	at android.app.Dialog.show(Dialog.java:325)
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
E/AndroidRuntime( 4829): 	at com.mapbox.maps.plugin.attribution.AttributionDialogManagerImpl.showTelemetryDialog(AttributionDialogManagerImpl.kt:130)
E/AndroidRuntime( 4829): 	at com.mapbox.maps.plugin.attribution.AttributionDialogManagerImpl.onClick(AttributionDialogManagerImpl.kt:100)
E/AndroidRuntime( 4829): 	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)
E/AndroidRuntime( 4829): 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
E/AndroidRuntime( 4829): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
E/AndroidRuntime( 4829): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
E/AndroidRuntime( 4829): 	at android.widget.AbsListView$3.run(AbsListView.java:4244)
E/AndroidRuntime( 4829): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime( 4829): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 4829): 	at android.os.Looper.loopOnce(Looper.java:205)
E/AndroidRuntime( 4829): 	at android.os.Looper.loop(Looper.java:294)
E/AndroidRuntime( 4829): 	at android.app.ActivityThread.main(ActivityThread.java:8177)
E/AndroidRuntime( 4829): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4829): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/AndroidRuntime( 4829): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
Test with package version `1.0.0-beta.3` and also using the repo example app.

**Comment by evil159** [comment]
Hi @vchrisb, thank you for your report! I was able to replicate the crash, we are taking it into our current work sprint.

**Comment by vchrisb** [comment]
works with `1.0.0`
