### ISSUE TITLE
Exception thrown after calling `dispose()` on MapboxMap

### ISSUE THREAD

**Issue by kalucky0** [mapbox/mapbox-maps-flutter#409]
## Environment
- Flutter version: `3.16.9`
- mapbox_maps_flutter version: `0.5.1`
- Device: `iPhone Simulator`
- OS: `iOS 17.2`

## Steps to Reproduce
- Navigate to a screen with MapWidget
- Pop the screen with MapWidget
Code: [GitHub Gist](https://gist.github.com/kalucky0/59f2649c482abd94abc5a2a1c78e6d2f)

## Description
I'm encountering an issue where an exception is thrown after exiting a screen and calling `dispose()` on `MapboxMap`. The exception message suggests that the `MapboxMap` object is being used after being disposed.

## Expected Behavior
After calling `dispose()` on a `MapboxMap` object, the object is disposed of properly and no exception is thrown.

## Actual Behavior
The following exception is thrown:

```yaml
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: A MapboxMap was used after being disposed.
Once you have called dispose() on a MapboxMap, it can no longer be used.
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.dispose (package:flutter/src/foundation/change_notifier.dart:375:27)
#3      MapboxMap.dispose (package:mapbox_maps_flutter/src/mapbox_map.dart:194:11)
#4      _MapWidgetState.dispose (package:mapbox_maps_flutter/src/map_widget.dart:208:18)
<asynchronous suspension>
```

**Comment by ilyosbekkk** [comment]
Any updates on this issue? I am also having the same issue in my app

**Comment by kalucky0** [comment]
The issue persists in [1.0.0](https://github.com/mapbox/mapbox-maps-flutter/releases/tag/1.0.0) release

**Comment by appinteractive** [comment]
Have the same issue, anyone any luck in dealing with it?

**Comment by appinteractive** [comment]
I solved it in my case by NOT calling `Map.dispose();` myself.

**Comment by kalucky0** [comment]
Doesn't that break when opening the same screen the second time?

**Comment by appinteractive** [comment]
> Doesn't that break when opening the same screen the second time?

Not for me, seems it is already called by the MapBox widget itself, so I have no issues with that. Seems the issue came from disposing it a second time.

**Comment by kmsbin** [comment]
When opening the same screen for the second time, there is another problem with symbols.

`
I/flutter ( 5458): MissingPluginException(No implementation found for method source#setFeature on channel plugins.flutter.io/mapbox_maps_0)
E/flutter ( 5458): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method source#setGeoJson on channel plugins.flutter.io/mapbox_maps_0)
E/flutter ( 5458): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #1      MethodChannelMapboxGl.setGeoJsonSource (package:mapbox_gl_platform_interface/src/method_channel_mapbox_gl.dart:526:5)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #2      MapboxMapController.setGeoJsonSource (package:mapbox_gl/src/controller.dart:312:5)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #3      AnnotationManager._setAll (package:mapbox_gl/src/annotation_manager.dart:84:7)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #4      AnnotationManager.add (package:mapbox_gl/src/annotation_manager.dart:103:5)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #5      MapboxMapController.addSymbol (package:mapbox_gl/src/controller.dart:624:5)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #6      _ControllerBase.updateTruckSymbol (controller.dart:342:24)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #7      _ControllerBase.setSymbols (controller.dart:414:5)
E/flutter ( 5458): <asynchronous suspension>
E/flutter ( 5458): #8      _ControllerBase.init.<anonymous closure>.<anonymous closure> (controller.dart:133:11)
E/flutter ( 5458): <asynchronous suspension>

`
I think the problem is around the mapbox_maps id

> Doesn't that break when opening the same screen the second time?

**Comment by gorkemhacioglu** [comment]
I do this;

```
late MapboxMap? _mapController;

  @override
  void dispose() {
    locationSubscription?.cancel();
    //_mapController.dispose();
    _mapController = null;

    super.dispose();
  }
  
  //and access with ?
 void getVisibleBounds(){
var visibleBounds = await _mapController?.coordinateBoundsForCamera(cameraState.toCameraOptions());
}
```

**Comment by ZinThantWin** [comment]
` if (mapboxController != null) {
      try {
        mapboxController = null;
        mapboxController?.dispose();
        debugPrint("Mapbox disposed successfully");
      } catch (e) {
        debugPrint("Error during Mapbox disposal: $e");
      }
    } else {
      debugPrint("Mapbox controller is already null or disposed.");
    }` try this

**Comment by ZinThantWin** [comment]
` if (mapboxController != null) {
      try {
        mapboxController = null;
        mapboxController?.dispose();
        debugPrint("Mapbox disposed successfully");
      } catch (e) {
        debugPrint("Error during Mapbox disposal: $e");
      }
    } else {
      debugPrint("Mapbox controller is already null or disposed.");
    }`
Try this

**Comment by ZinThantWin** [comment]
try this
`if (mapboxController != null) 
{ try 
   { 
      mapboxController = null; 
      mapboxController?.dispose(); 
      debugPrint("Mapbox disposed successfully"); 
} catch (e) { 
     debugPrint("Error on Mapbox disposal==> $e");
   } 
} else { 
     debugPrint("Mapbox controller is already null or disposed"); 
}`
