### ISSUE TITLE
getStyleImage & hasStyleImage methods not responding

### ISSUE THREAD

**Issue by devmobile-vulog** [mapbox/mapbox-maps-flutter#411]
### **Environment**
Flutter version: 3.13.0
mapbox_maps_flutter version: 1.0.0-beta.3
Device: Samsung Galaxy A53
OS: Android 14
### **Steps to Reproduce**
Call `getStyleImage(imageId)` or `hasStyleImage(imageId)` methods from StyleManager

### **Expected Behavior**
These two methods should return either a `Future<MbxImage?>` or a `Future<bool>`

### **Actual Behavior**
`getStyleImage(imageId)` actually throw the following exception: 
`E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): Failed to handle message
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): java.lang.IllegalStateException: Reply already submitted
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:435)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler$1.reply(BasicMessageChannel.java:224)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$33.success(FLTMapInterfaces.java:10964)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$33.success(FLTMapInterfaces.java:10961)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at com.mapbox.maps.mapbox_maps.StyleController.getStyleImage(StyleController.kt:487)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$-CC.lambda$setUp$42(FLTMapInterfaces.java:10973)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$$ExternalSyntheticLambda30.onMessage(Unknown Source:2)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:219)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at android.os.Handler.handleCallback(Handler.java:958)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at android.os.Looper.loopOnce(Looper.java:230)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at android.os.Looper.loop(Looper.java:319)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at android.app.ActivityThread.main(ActivityThread.java:8893)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at java.lang.reflect.Method.invoke(Native Method)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
E/BasicMessageChannel#dev.flutter.pigeon.mapbox_maps_flutter.StyleManager.getStyleImage(13885): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
E/DartMessenger(13885): Uncaught exception in binary message listener`

`hasStyleImage(imageId)` returns nothing

Thanks.

**Comment by chris-wickens** [comment]
Same issue on Pixel 6, at least for hasStyleImage. Goes into the StyleManager and never comes out, can't see what's happening.

**Comment by FredKup** [comment]
Facing the same issue on Android. 
Could someone dig into it, because it is a blocker for us. 

Thanks.

**Comment by chris-wickens** [comment]
This issue is still present in the v1 release, and is preventing me from updating.

**Comment by deandreamatias** [comment]
I also have this issue on Samsung A53 5G

**Comment by paulVulog** [comment]
Just tested using the Mapbox V1.1.0-RC1 sample app, and everything looks good : 
HasStyleImage return as expected 
and
GetStyleImage do not throw exception. 

Anyone can confirm ?

_Reproduced on V1.0.0 and V1.0.0-RC1_

**Comment by chris-wickens** [comment]
@paulVulog just tested on the commit you specified and hasStyleImage is working correctly again. Thanks!

**Comment by paulVulog** [comment]
Looks like it's correctly fixed on the official V1.1.0 release 🎉

**Comment by O-Hannonen** [comment]
Closing as fixed. BTW v3 will feature some ergonomics improvements for the style image APIs, being more explicit about the encoding format and offering utilities to pass images in multiple different encodings!
