### ISSUE TITLE
Mapbox on Flutter Crashes Regularly - Bug with Point Annotation Anchors

### ISSUE THREAD

**Issue by penhorwood** [mapbox/mapbox-maps-flutter#417]
When displaying a point on map via Point_annotation while in debug mode I am getting this error message.  I have tried this with the .5.1 release and the 1.0.0 rc1 they both seem to have the issue.

Flutter 3.19.0
Android device - Samsung S10

The problem doesn't surface if I run this in release mode but it make debugging a major pain.

Cause: null, Stacktrace: java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT]
	at com.mapbox.maps.extension.style.layers.properties.generated.TextAnchor$Companion.valueOf(Property.kt:662)
	at com.mapbox.maps.plugin.annotation.generated.PointAnnotation.getTextAnchor(PointAnnotation.kt:353)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationControllerKt.toFLTPointAnnotation(PointAnnotationController.kt:848)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationController.create(PointAnnotationController.kt:61)
	at com.mapbox.maps.pigeons.FLTPointAnnotationMessager$_PointAnnotationMessager.lambda$setUp$0(FLTPointAnnotationMessager.java:2261)
	at com.mapbox.maps.pigeons.FLTPointAnnotationMessager$_PointAnnotationMessager$$ExternalSyntheticLambda0.onMessage(Unknown Source:2)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by smc66** [comment]
Same issue here.  Android only - no problems on iOS.

**Comment by penhorwood** [comment]
This bug is still happening on version 2.2.  This should be an easy fix.

**Comment by penhorwood** [comment]
I seem to have reported this twice.  Here is the other ticket:  https://github.com/mapbox/mapbox-maps-flutter/issues/161

Either way it is still happening on 2024-08-22.

**Comment by penhorwood** [comment]
I thought we had this one behind us.  When using VC Code and debug mode via the UI ( not from the command line ).  When I display an PointAnnotationOptions with TextAnchor.BOTTOM_LEFT I get this error.

PlatformException (PlatformException(RuntimeException, java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT], Cause: null, Stacktrace: java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT]
	at com.mapbox.maps.extension.style.layers.properties.generated.TextAnchor$Companion.valueOf(Property.kt:668)
	at com.mapbox.maps.plugin.annotation.generated.PointAnnotation.getTextAnchor(PointAnnotation.kt:347)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationControllerKt.toFLTPointAnnotation(PointAnnotationController.kt:1707)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationController.create(PointAnnotationController.kt:56)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion.setUp$lambda$1$lambda$0(PointAnnotationMessenger.kt:1263)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion.$r8$lambda$uhPziMpx5_-1auyqldLE0nqFU2A(Unknown Source:0)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion$$ExternalSyntheticLambda0.onMessage(D8$$SyntheticClass:0)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
, null))

**Comment by penhorwood** [comment]
Should note.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.3, on Microsoft Windows [Version 10.0.19045.4894], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)      
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[√] Android Studio (version 2024.1)
[√] Connected device (1 available)
[√] Network resources

JDK - is the one from Android Studio

mapbox_maps_flutter: ^2.3.0

**Comment by penhorwood** [comment]
**Issues is still happen on the latest version mapbox_maps_flutter: 2.4.1**

Stack trace from today.  I notice it while in debug mode but I know it also happens in production because I see the errors in my Sentry errors.

PlatformException (PlatformException(RuntimeException, java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT], Cause: null, Stacktrace: java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT]
	at com.mapbox.maps.extension.style.layers.properties.generated.TextAnchor$Companion.valueOf(Property.kt:668)
	at com.mapbox.maps.plugin.annotation.generated.PointAnnotation.getTextAnchor(PointAnnotation.kt:350)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationControllerKt.toFLTPointAnnotation(PointAnnotationController.kt:1707)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationController.create(PointAnnotationController.kt:56)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion.setUp$lambda$1$lambda$0(PointAnnotationMessenger.kt:1259)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion.$r8$lambda$uhPziMpx5_-1auyqldLE0nqFU2A(Unknown Source:0)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion$$ExternalSyntheticLambda0.onMessage(D8$$SyntheticClass:0)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
, null))

**Comment by penhorwood** [comment]
The generates an error in Debug mode that is visible.  Running the app unattached from the computer Sentry is picking up this bug too.

This is happening on the latest version.

**Comment by penhorwood** [comment]
PlatformException(RuntimeException, java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT]

This is showing up on user phone and being reported as a crash.  **Since this is an official value of TextAnchor it would be great if it worked.**

**Comment by penhorwood** [comment]
PlatformException (PlatformException(RuntimeException, java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT], Cause: null, Stacktrace: java.lang.RuntimeException: TextAnchor.valueOf does not support [BOTTOM-LEFT]
	at com.mapbox.maps.extension.style.layers.properties.generated.TextAnchor$Companion.valueOf(Property.kt:904)
	at com.mapbox.maps.plugin.annotation.generated.PointAnnotation.getTextAnchor(PointAnnotation.kt:376)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationControllerKt.toFLTPointAnnotation(PointAnnotationController.kt:1753)
	at com.mapbox.maps.mapbox_maps.annotation.PointAnnotationController.create(PointAnnotationController.kt:56)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion.setUp$lambda$3$lambda$2(PointAnnotationMessenger.kt:1399)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion.$r8$lambda$LpRAJ4o4XmW8WWrBzIjWg95dWBE(Unknown Source:0)
	at com.mapbox.maps.mapbox_maps.pigeons._PointAnnotationMessenger$Companion$$ExternalSyntheticLambda190.onMessage(D8$$SyntheticClass:0)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
