### ISSUE TITLE
[BUG] MissingPluginException ... platform#releaseMethodChannels

### ISSUE THREAD

**Issue by LorenzSchueler** [mapbox/mapbox-maps-flutter#550]
When poping a Widget which holds a MapWidget I get the following error:

```
MissingPluginException(No implementation found for method platform#releaseMethodChannels on channel plugins.flutter.io)
```

stack trace:
```
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      _MapboxMapsPlatform.dispose (package:mapbox_maps_flutter/src/mapbox_maps_platform.dart:102:5)
<asynchronous suspension>
```

The line which causes the issue https://github.com/mapbox/mapbox-maps-flutter/blob/1e628169688a4f2081bdf4bb5842853b2988bb20/lib/src/mapbox_maps_platform.dart#L102 was introduced in #383.

flutter: `3.22.0`
mapbox_maps_flutter: `2.0.0-rc.1`
platform: Android 14

@evil159 do you know if this is caused by misuse on my side or is this indeed a bug?

**Comment by RAglx** [comment]
Since we also have this error, it would be good to know if we are doing something wrong. Or if it is an actual bug in SDK, which will be corrected in due course.

BTW: The fix provided by @LorenzSchueler does work for us too.
