### ISSUE TITLE
I'm trying to add an image (Uint8List) to the maps style, but i get a error: Throwable, java.lang.Throwable: mismatched image size, Cause: null, Stacktrace: java.lang.Throwable: mismatched image size

### ISSUE THREAD

**Issue by zhaoMing8** [mapbox/mapbox-maps-flutter#555]
I'm trying to add an image (Uint8List) to the maps style, so that I can reference it later in a feature when I assemble a source geojson. This is what I tried:

Andriod 13.0.

`
ByteData byteData =
        await rootBundle.load('assets/map_icons/home.png');
    Uint8List image = byteData.buffer.asUint8List();
    // So far everything is okay, the list is correct.
    // But here I struggle with understanding what half of the properties do. The next line throws an error.
    await mapController.style.addStyleImage(
      assetName, // A string (which I later use to reference the image in a geojson source)
      1,
      MbxImage(width: 50, height: 50, data: image),
      false,
      [],
      [],
      null,
    );
`

The error thrown is:

`
PlatformException (PlatformException(Throwable, java.lang.Throwable: mismatched image size, Cause: null, Stacktrace: java.lang.Throwable: mismatched image size
	at com.mapbox.maps.mapbox_maps.StyleController.addStyleImage$lambda-49(StyleController.kt:641)
	at com.mapbox.maps.mapbox_maps.StyleController.$r8$lambda$9qzAKUZTMYPcXQ8_jKe8hkSxnyU(Unknown Source:0)
	at com.mapbox.maps.mapbox_maps.StyleController$$ExternalSyntheticLambda0.onStyleLoaded(Unknown Source:17)
	at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:355)
	at com.mapbox.maps.mapbox_maps.StyleController.addStyleImage(StyleController.kt:610)
	at com.mapbox.maps.mapbox_maps.StyleController.addStyleImage(StyleController.kt:17)
	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$-CC.lambda$setup$34(FLTMapInterfaces.java:7898)
	at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$$ExternalSyntheticLambda20.onMessage(Unknown Source:2)
	at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:217)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:250)
	at android.app.ActivityThread.main(ActivityThread.java:7806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
, null))
`

**Comment by felixkrautschuk** [comment]
You could try this:

```
ByteData byteData = await rootBundle.load('assets/map_icons/home.png');
Uint8List image = byteData.buffer.asUint8List();

final parsedImage = await decodeImageFromList(image);
final mbxImage = MbxImage(data: image, height: parsedImage.height, width: parsedImage.width);

await mapController.style.addStyleImage(
      assetName,
      1,
      mbxImage,
      false,
      [],
      [],
      null,
);
```

**Comment by zhaoMing8** [comment]
> You could try this:
> 
> ```
> ByteData byteData = await rootBundle.load('assets/map_icons/home.png');
> Uint8List image = byteData.buffer.asUint8List();
> 
> final parsedImage = await decodeImageFromList(image);
> final mbxImage = MbxImage(data: image, height: parsedImage.height, width: parsedImage.width);
> 
> await mapController.style.addStyleImage(
>       assetName,
>       1,
>       mbxImage,
>       false,
>       [],
>       [],
>       null,
> );
> ```

Oh! Thanks! That worked for me.

**Comment by felixkrautschuk** [comment]
Sorry, I am not able to explain you that as I am not a Flutter expert myself.
But the same error occurred on my side some days ago and I found that solution/workaround somewhere in StackOverflow, so I was able to continue my work at least.

**Comment by zhaoMing8** [comment]
> Sorry, I am not able to explain you that as I am not a Flutter expert myself. But the same error occurred on my side some days ago and I found that solution/workaround somewhere in StackOverflow, so I was able to continue my work at least.

ohh, A strange question. thank you very much for help me  to continue my work!

**Comment by felixkrautschuk** [comment]
@zhaoMing8 Now that you got it working, I need to ask you a question... :)
Do the images appear sharp in your app? 

On my side, the SymbolLayer icons look very blurry on Android and iOS (device and simulator) and I have no idea why.
I also tried that custom-icon.png asset from the example-app but that does not look sharp as well.
How is your experience?

**Comment by zhaoMing8** [comment]
> @zhaoMing8 Now that you got it working, I need to ask you a question... :) Do the images appear sharp in your app?
> 
> On my side, the SymbolLayer icons look very blurry on Android and iOS (device and simulator) and I have no idea why. I also tried that custom-icon.png asset from the example-app but that does not look sharp as well. How is your experience?

sorry, l also don`t have a good idea. but it seems to be working normal on ios

**Comment by manukumarsb7** [comment]
Thanks worked for me too.

my issue was 
```dart
Unhandled Exception: PlatformException(Throwable, java.lang.Throwable: Raster image reference has invalid data size, Cause: null, Stacktrace: java.lang.Throwable: Raster image reference has invalid data size
```

**Comment by felixkrautschuk** [comment]
@manukumarsb7 are the style images displayed sharp on your side? Our marker icons still look blurry and I don't know why

**Comment by felixkrautschuk** [comment]
Just in case anyone else encounters this problem: I found the cause for my icons appearing blurry.

`await rootBundle.load('assets/map_icons/home.png')` will not handle the resolution-aware lookup automatically (2.0x/, 3.0x/, etc.), it will always load the 'base' icon, that's why my icons appeared blurry on devices with higher pixel ratio.


So the better approach is:
```
Future<void> addMapStyleImage(String imagePath) async {
    final double devicePixelRatio = MediaQuery.of(context).devicePixelRatio;
    final AssetImage assetImage = AssetImage(imagePath);

    //depending on device pixel ratio, determine which variant of the asset should be taken (root, 2.0x, 3.0x, ...)
    final AssetBundleImageKey key = await assetImage.obtainKey(ImageConfiguration(devicePixelRatio: devicePixelRatio));

    final ByteData bytes = await key.bundle.load(key.name);
    final Uint8List imageData = bytes.buffer.asUint8List();
    final ui.Image parsedImage = await decodeImageFromList(imageData);
    final MbxImage mbxImage = MbxImage(data: imageData, height: parsedImage.height, width: parsedImage.width);
    await mapboxMap?.style.addStyleImage(imageName, devicePixelRatio, mbxImage, false, [], [], null);
}
```
