### ISSUE TITLE
I want to use addLayer, but i get a error: PlatformException(java.lang.Throwable: value must be a number, Throwable, Cause: null, Stacktrace: java.lang.Throwable: value must be a number

### ISSUE THREAD

**Issue by zhaoMing8** [mapbox/mapbox-maps-flutter#560]
I want to use addLayer, but i get a eror.

Android: 13.0
flutter: 3.3.16

code this:

```dart
controller!.style.addLayer(SymbolLayer(
    sourceId: 'me',
    id: 'me',
    iconImage: 'me',
    iconAllowOverlap: true,
    iconAnchor: IconAnchor.CENTER,
  ));

  controller!.style.setStyleLayerProperty("me", "icon-size", {
    'stops': [
      [0.0, 1 / 2],
      [20.0, 1],
    ],
    'base': 2,
  });
```

the error message this:

```dart
Error :  PlatformException(java.lang.Throwable: value must be a number, Throwable, Cause: null, Stacktrace: java.lang.Throwable: value must be a number
at com.mapbox.maps.mapbox_maps.StyleController.setStyleLayerProperty(StyleController.kt:227)
at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager.lambda$setUp$22(FLTMapInterfaces.java:10502)
at com.mapbox.maps.pigeons.FLTMapInterfaces$StyleManager$$ExternalSyntheticLambda5.onMessage(Unknown Source:2)
at io.flutter.plugin.common.BasicMessageChannel$IncomingMessageHandler.onMessage(BasicMessageChannel.java:261)
at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8503)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
```

**Comment by evil159** [comment]
@zhaoMing8 I think your `interpolate` expression is not up to spec, you can find an example here https://docs.mapbox.com/mapbox-gl-js/example/change-building-color-based-on-zoom-level/
