### ISSUE TITLE
Android App Crashing on Offline Mode

### ISSUE THREAD

**Issue by Nabinda** [mapbox/mapbox-maps-flutter#585]
I was testing the offline beta, And when downloading the map using the example provided by the package itself, Its crashing with the following logs:

```
W/System.err( 7582): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Unspecified Wor
W/System.err( 7582): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1493)
W/System.err( 7582): 	at io.flutter.embedding.engine.FlutterJNI.dispatchEmptyPlatformMessage(FlutterJNI.java:1088)
W/System.err( 7582): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:279)
W/System.err( 7582): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:446)
W/System.err( 7582): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:206)
W/System.err( 7582): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.endOfStream(EventChannel.java:270)
W/System.err( 7582): 	at com.mapbox.maps.mapbox_maps.offline.TileStoreController.loadTileRegion$lambda$3(TileStoreController.kt:51)
W/System.err( 7582): 	at com.mapbox.maps.mapbox_maps.offline.TileStoreController.$r8$lambda$wCTkOSC8bPdDCC-OkXnOcEHqoV4(Unknown Source:0)
W/System.err( 7582): 	at com.mapbox.maps.mapbox_maps.offline.TileStoreController$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
E/gralloc4( 7582): Empty SMPTE 2094-40 data
D/AndroidRuntime( 7582): Shutting down VM
E/AndroidRuntime( 7582): FATAL EXCEPTION: main
E/AndroidRuntime( 7582): Process: com.mapbox.maps.flutter.example, PID: 7582
E/AndroidRuntime( 7582): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Unspecified Wor
E/AndroidRuntime( 7582): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:1493)
E/AndroidRuntime( 7582): 	at io.flutter.embedding.engine.FlutterJNI.dispatchEmptyPlatformMessage(FlutterJNI.java:1088)
E/AndroidRuntime( 7582): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:279)
E/AndroidRuntime( 7582): 	at io.flutter.embedding.engine.dart.DartExecutor$DefaultBinaryMessenger.send(DartExecutor.java:446)
E/AndroidRuntime( 7582): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:206)
E/AndroidRuntime( 7582): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.endOfStream(EventChannel.java:270)
E/AndroidRuntime( 7582): 	at com.mapbox.maps.mapbox_maps.offline.TileStoreController.loadTileRegion$lambda$3(TileStoreController.kt:51)
E/AndroidRuntime( 7582): 	at com.mapbox.maps.mapbox_maps.offline.TileStoreController.$r8$lambda$wCTkOSC8bPdDCC-OkXnOcEHqoV4(Unknown Source:0)
E/AndroidRuntime( 7582): 	at com.mapbox.maps.mapbox_maps.offline.TileStoreController$$ExternalSyntheticLambda5.run(D8$$SyntheticClass:0)
W/flutter.example( 7582): type=1400 audit(0.0:1540124): avc: denied { search } for name="miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
W/flutter.example( 7582): type=1400 audit(0.0:1540125): avc: denied { search } for name="miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
W/flutter.example( 7582): type=1400 audit(0.0:1540126): avc: denied { search } for name="miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
W/flutter.example( 7582): type=1400 audit(0.0:1540127): avc: denied { search } for name="miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
W/flutter.example( 7582): type=1400 audit(0.0:1540128): avc: denied { search } for name="miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
W/flutter.example( 7582): type=1400 audit(0.0:1540129): avc: denied { search } for name="miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
W/OOMEventManagerFK( 7582): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
W/flutter.example( 7582): type=1400 audit(0.0:1540130): avc: denied { getattr } for path="/data/miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
W/flutter.example( 7582): type=1400 audit(0.0:1540131): avc: denied { search } for name="miuilog" dev="dm-40" ino=512753 scontext=u:r:untrusted_app:s0:c204,c260,c512,c768 tcontext=u:object_r:data_log_file:s0 tclass=dir permissive=0 app=com.mapbox.maps.flutter.example
E/gralloc4( 7582): Empty SMPTE 2094-40 data
I/Process ( 7582): Process is going to kill itself!
I/Process ( 7582): java.lang.Exception
I/Process ( 7582): 	at android.os.Process.killProcess(Process.java:1330)
I/Process ( 7582): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:195)
I/Process ( 7582): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
I/Process ( 7582): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
I/Process ( 7582): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
I/Process ( 7582): Sending signal. PID: 7582 SIG: 9
Lost connection to device.
```

Flutter Version: 3.22.0
Dart Version: 3.4.0
Crash Device: Redmi Note 11s (Xiaomi Hyper OS)
Android Version: 13

**Comment by Zeldroxe** [comment]
Same here :/

Flutter Version: 3.22.2
Dart Version: 3.4.3
Crash Device: Samsung S21 Ultra (One UI 6.1)
Android Version: 14
