### ISSUE TITLE
PlatformException recreating_view

### ISSUE THREAD

**Issue by jnorkus** [mapbox/mapbox-maps-flutter#811]
After upgrading to Flutter 3.27.0 I am getting this error on an iOS simulator (haven't tested on a device) after hot restarting. Also, the map view does not properly load.

Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view id: '0', null)

**Comment by evil159** [comment]
Hi @jnorkus, I can't reproduce the issue with Flutter 3.27, could you share a code snippet?

**Comment by jnorkus** [comment]
> Hi @jnorkus, I can't reproduce the issue with Flutter 3.27, could you share a code snippet?

I was able to reproduce using the example project.

1. Run on iOS simulator
2. Go to "Display a simple map"
3. Do a hot restart
4. Go to "Display a simple map"

**Comment by evil159** [comment]
@jnorkus thank you for the clarification, still no luck on my side, could you share iOS and Xcode version you are using?

**Comment by jnorkus** [comment]
> @jnorkus thank you for the clarification, still no luck on my side replicating this, could you share iOS and Xcode version you are using?

iOS 17.2
Xcode 15.2

I'll try upgrading my macOS to get the latest version of Xcode and see if that helps.

**Comment by jnorkus** [comment]
Same results on:
iOS 18.2
Xcode 16.2

Reproducable on the example app in this repo as before. Please note that you have to do a hot restart (not hot reload).

**Comment by ludovicjamet** [comment]
I got the same issue, and just so you know downgrading to flutter v3.24.5 solved the issue. Do you need help to reproduce @evil159?

**Comment by KonstantinDubrouski** [comment]
Same issue

**Comment by jasperdemmers** [comment]
I've got the same issue on MapBox 2.4.0, Xcode 16.0
```
Flutter 3.27.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 17025dd882 (3 weeks ago) • 2024-12-17 03:23:09 +0900
Engine • revision cb4b5fff73
Tools • Dart 3.6.0 • DevTools 2.40.2

**Comment by Ekram-Muahammad** [comment]
Same issue wit flutter 3.27.1

**Comment by evil159** [comment]
Seems to be a bug in Flutter itself https://github.com/flutter/flutter/issues/110381

**Comment by cgalindonewminds** [comment]
Upgrading to v3.27.2 seems to solve the problem also

**Comment by ludovicjamet** [comment]
Any news on this one, is it really a Flutter issue?

**Comment by GamxXamg** [comment]
Any news ? Starting to happen with flutter 3.27.X

**Comment by favazHF** [comment]
Today was merge a solution I think https://github.com/flutter/flutter/issues/163935, but is just for iOS

**Comment by PaulAllanSturm** [comment]
There were two separate fixes, one for iOS and one for macOS. Both have been merged to main. They should be available in the next major release.

macOS: https://github.com/flutter/flutter/issues/110381
iOS: https://github.com/flutter/flutter/issues/163935

**Comment by Salimer** [comment]
I am facing this issue when debugging on iPhone 13 Pro with flutter 3.29.1 

[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: PlatformException(recreating_view, trying to create an already created view, view id: '8', null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
message_codecs.dart:652
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:370:18)
platform_channel.dart:370
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:243:5)
platform_views.dart:243
<asynchronous suspension>
#3      _DarwinViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:933:36)
platform_view.dart:933
<asynchronous suspension>


using google map widget like this " SizedBox(
                  width: 100,
                  height: 100,
                  child: GoogleMap(
                    initialCameraPosition: CameraPosition(
                      target: LatLng(address.latitude, address.longitude),
                      zoom: 14,
                    ),
                    zoomControlsEnabled: false,
                    scrollGesturesEnabled: false,
                    tiltGesturesEnabled: false,
                    rotateGesturesEnabled: false,
                    myLocationButtonEnabled: false,
                  ),
                ),"


upgrading to flutter 3.29.2 and will test

**Comment by Salimer** [comment]
Still same issue on flutter 3.29.2, I added unique keys but still.

**Comment by PaulAllanSturm** [comment]
The fixes are in release 3.30.0-0.1.pre (the 3.30 beta release). They'll also be in the next major stable release, which will be presumably 3.31 or 3.32.

**Comment by moorphism-ltd** [comment]
Still same issue on Flutter 3.29.2 • channel stable, waiting for stable release 3.31+

**Comment by andrescastane** [comment]
Same issue on Flutter 3.29.1. This error seems to be very specific to embedded views like maps or iframes. I get the error in a Mac app using the flutter_inappwebview package, and I get the same error using maps on iOS. It may be specific to iOS and macOS.

I also find that when I reload several times, the number of IDs increases until I find one that works correctly after several refreshes.

`PlatformException(recreating_view, trying to create an already created view, view id: '1 or 2 or 3 or 4 ... n', null)`

I'm waiting for the new version. It seems they've already fixed it, but it hasn't been merged into the main version yet. Hopefully it'll be fixed soon.

**Comment by niteshneupane** [comment]
update?

**Comment by pavleralic** [comment]
Is there any update regarding this topic?

**Comment by PaulAllanSturm** [comment]
The underlying bug in Flutter was fixed in Flutter 3.30 (beta). It's not being backported to the 3.29 series. You have the option of using the latest Flutter beta, which is Flutter 3.32. Or waiting for whatever the next major stable release will be, which might be Flutter 3.33.

**Comment by RoyalBosS-Ayush** [comment]
I'm facing the same issue. It seems to be a Flutter related problem rather than a Mapbox.

**Comment by O-Hannonen** [comment]
Closing this as the activity on this issue stopped after the underlying problem was fixed in Flutter. Thanks for reporting and the active discussion!
