### ISSUE TITLE
Null Pointer Exception on addStyleImage

### ISSUE THREAD

**Issue by cfsbhawkins** [mapbox/mapbox-maps-flutter#96]
Im looking to getting away from loading all of my custom icons each time I place a point annotation on the map, an instead loading them at map load time. So I am using an example I found on another issue here. ButI keep getting this NPE that crashes the app. 

I am using the Flutter image library to get the dimensions, and to load the image from assets. The image is an SVG that is converted to PNG then loaded in.

`  _loadMapMarkers() {
    MarkerType.values.forEach((marker) async {
      final image = await marker.getImageAsset(context);
      if (image != null && image.isValid) {
        final imgData = image.toUint8List();
        if (imgData.isNotEmpty) {
          await _mapboxMap?.style.addStyleImage(
            'core-${marker.name}',
            1,
            MbxImage(width: image.width,
                height: image.height,
                data: imgData),
            true,
            [],
            [],
            null,
          );
        }
      }
    });
  }`

E/AndroidRuntime( 7430): java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.Bitmap$Config android.graphics.Bitmap.getConfig()' on a null object reference
E/AndroidRuntime( 7430): 	at com.mapbox.maps.mapbox_maps.StyleController.addStyleImage$lambda$49(StyleController.kt:616)
E/AndroidRuntime( 7430): 	at com.mapbox.maps.mapbox_maps.StyleController.$r8$lambda$mWgjakF-UGxkOYHa3LTLVGyx9a4(Unknown Source:0)
E/AndroidRuntime( 7430): 	at com.mapbox.maps.mapbox_maps.StyleController$$ExternalSyntheticLambda0.onStyleLoaded(Unknown Source:17)
E/AndroidRuntime( 7430): 	at com.mapbox.maps.StyleObserver.onStyleLoaded(StyleObserver.kt:103)
E/AndroidRuntime( 7430): 	at com.mapbox.maps.NativeObserver.notify(NativeObserver.kt:63)
E/AndroidRuntime( 7430): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime( 7430): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime( 7430): 	at android.os.Looper.loopOnce(Looper.java:161)
E/AndroidRuntime( 7430): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 7430): 	at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime( 7430): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7430): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 7430): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by cfsbhawkins** [comment]
Closing due to bad PNGs

**Comment by cfsbhawkins** [comment]
I ended up using PNGs, the SVG loader to PNG conversion caused some issues for me from time to time its slow until the SVG is in its cache, the other thing I did load it into Style Image the first time I go to insert a poi marker onto the map, kept running into issues while the map was loading. 

    Future<void> insertMarker(Marker marker) async {
        if(_pointAnnotationManager == null){
          return;
        }

    if(!_hasLoadedMarkers){
      _hasLoadedMarkers = true;

      await MarkerType.session.getImageAsset(context).then((sessionByteData) {
        final sessionImage = img.decodePng(sessionByteData.buffer.asUint8List());
        _mapboxMap?.style.addStyleImage('myIcon-${MarkerType.session.name}', 1, MbxImage(width: sessionImage!.width, height: sessionImage.height, data: sessionByteData.buffer.asUint8List()), true, [], [], null,);
      });
      
The getImageAsset is just an extension that loads a PNG using DefaultAssetBundle.of(context).load(assetFile);
      
When placing an image on map, all I need to do is set iconImage to the String I generated above.

**Comment by cfsbhawkins** [comment]
From what I have found with other call backs in the library stay as synchronous as possible, I had originally had done a lot of the onMapLoaded and stuff in async functions, that led to tons of race conditions. like you said the .then has been a trick to get a lot working.
